services:
  - type: web
    name: pointage-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /api
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
